### Login 1

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "Agus",
  "password": "jose123"
}

### Login 2

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "jor",
  "password": "123"
}

### obtener todos los users

GET http://localhost:3000/api/users


### crear nuevo user

POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJBZ3VzIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzM2ODY1NTI3fQ.CSybUj7b4pzzdLVS4uQXBW1pxg0YJFLpgWKVcS2jS_M

{
  "username": "Silvi",
  "password": "123",
  "is_admin": "0"
}