### obtener todos los users

GET http://localhost:3000/api/users


### crear nuevo user

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Mati",
  "password": "jose123",
  "is_admin": "0"
}

### Login

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "Agus",
  "password": "jose123",
  "is_admin": "0"
}