### ID

@id = {{ createProject.response.body.data.id }}

### obtener todos los project

GET http://localhost:3000/api/projects
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzY1MjR9.0ZyOZYWTpuwK-XyeUvkLAZUloNewlX6T4O8zA9Bj-8k


### obtener un project

GET http://localhost:3000/api/projects/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY0NDUwMTR9.E_I1cI_Ss7GaeURmATd9Tok9n_qIhctbUuGS425Bt0w


### crear nuevo project

POST http://localhost:3000/api/projects
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzY1MjR9.0ZyOZYWTpuwK-XyeUvkLAZUloNewlX6T4O8zA9Bj-8k

{
  "name": "Los jose",
  "description": "Empresa del cuyo",
  "wiki": "",
  "creation_date": "2025-01-13"
}

### modificar un project con PUT (Idempotente y recurso completo)

PUT http://localhost:3000/api/projects/14
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzY1MjR9.0ZyOZYWTpuwK-XyeUvkLAZUloNewlX6T4O8zA9Bj-8k


{
  "name": "Familia Jose",
  "description": "Empresa de Rosario, Santa Fe",
  "wiki": "Esta es la wiki",
  "creation_date": "2025-01-13"
}

### modificar un project con PATCH (Recurso parcial)

PATCH http://localhost:3000/api/projects/6
Content-Type: application/json

{
  "wiki": "Esta es la wiki de Wiener"
}

### borrar un project

DELETE http://localhost:3000/api/projects/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzY1MjR9.0ZyOZYWTpuwK-XyeUvkLAZUloNewlX6T4O8zA9Bj-8k



### dirección inexistente

GET http://localhost:3000/api/projectss


/// docker run --name quickesticket -e MYSQL_ROOT_HOST='%' -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -e MYSQL_PASSWORD="agus" -e MYSQL_USER="agus" -e MYSQL_DATABASE='quickesticket' -p 3307:3307 -d mysql

/// docker run --name agus_mysql -e MYSQL_ROOT_HOST='%' -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -e MYSQL_PASSWORD="agus" -e MYSQL_USER="agus" -e MYSQL_DATABASE='quickesticket' -p 3306:3306 -d mysql