
### obtener todos los ticket

GET http://localhost:3000/api/tickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzgxMTF9.0JoTq4p_cmCXerKIXQ9Ltt_4Fd28VvnaJYls0v-JbIA

### obtener un ticket

GET http://localhost:3000/api/tickets/73
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzgxMTF9.0JoTq4p_cmCXerKIXQ9Ltt_4Fd28VvnaJYls0v-JbIA

### crear nuevo ticket

POST http://localhost:3000/api/tickets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzgxMTF9.0JoTq4p_cmCXerKIXQ9Ltt_4Fd28VvnaJYls0v-JbIA

{
  "project": 1,
  "creator": 1,
  "beginning_date": "2025-01-13",
  "state": 4,
  "title": "Ticket con jwt",
  "description": "Este es el primer ticket creado con autenticación jwt"
}

### modificar un ticket con PUT

PUT http://localhost:3000/api/tickets/73
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzgxMTF9.0JoTq4p_cmCXerKIXQ9Ltt_4Fd28VvnaJYls0v-JbIA

{
  "description": "Este es el primer ticket creado con autenticación jwt. Descripción modificada del ticket"
}

### borrar un ticket

DELETE http://localhost:3000/api/tickets/71
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndXMiLCJpYXQiOjE3MzY3NzgxMTF9.0JoTq4p_cmCXerKIXQ9Ltt_4Fd28VvnaJYls0v-JbIA

### obtener todos los ticket states

GET http://localhost:3000/api/ticket-states

/// docker run --name quickesticket -e MYSQL_ROOT_HOST='%' -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -e MYSQL_PASSWORD="agus" -e MYSQL_USER="agus" -e MYSQL_DATABASE='quickesticket' -p 3307:3307 -d mysql

/// docker run --name agus_mysql -e MYSQL_ROOT_HOST='%' -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -e MYSQL_PASSWORD="agus" -e MYSQL_USER="agus" -e MYSQL_DATABASE='quickesticket' -p 3306:3306 -d mysql